# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-17 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('blogs', '0002_auto_20161017_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
