# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-17 21:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('blogs', '0003_auto_20161017_2142'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='content_type',
            new_name='message_type',
        ),
    ]
