# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-17 22:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('blogs', '0004_auto_20161017_2159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='message_type',
            new_name='content_type',
        ),
        migrations.AlterField(
            model_name='like',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
